Disable strict iterators for this one file, I see no other way.
The error was:
dijkstra_shortest_paths.hpp:422:65: error: no type named ‘value_type’ in ‘struct boost::property_traits<QVector<int>::iterator>’
(but trying to define that, leads to missing get/put methods...)