compile:
error: floating-point literal cannot appear in a constant-expression

BTW, why you don't use M_PI from cmath? If this is due to MSVC then the define 
_USE_MATH_DEFINES is your friend.